# Generated by Django 3.2.9 on 2021-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('date_joined', models.DateField(verbose_name='С каких пор работает')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='media/persons', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='PersonOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(verbose_name='С каких пор работает')),
                ('description', models.TextField(verbose_name='Описание')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='media/persons', verbose_name='Фото')),
                ('age', models.PositiveIntegerField(default=16)),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/project')),
                ('description', models.TextField()),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('date', models.DateField()),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
