# Generated by Django 3.2.9 on 2021-11-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название должности')),
                ('slug', models.SlugField(verbose_name='Слаг')),
            ],
        ),
        migrations.AddField(
            model_name='personin',
            name='age',
            field=models.PositiveIntegerField(default=16, verbose_name='Возрост'),
        ),
        migrations.AddField(
            model_name='personin',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personout',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
