# Generated by Django 3.2.9 on 2021-11-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211128_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personin',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='personout',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.position', verbose_name='Должность'),
        ),
    ]
