# Generated by Django 3.2.9 on 2021-11-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211128_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonOut',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='PersonIn',
        ),
    ]
