# Generated by Django 3.2.9 on 2021-11-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211128_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(default=16, verbose_name='Возраст'),
        ),
    ]
